# Cloud Build configuration for deploying to Google Cloud
# This file tells Google Cloud Build how to build and deploy our Docker container

steps:
  # Use the official Docker builder to build our container image
  - name: 'gcr.io/cloud-builders/docker'
    # Specify Dockerfile path (-f) and build context because we're in a monorepo
    # The prototype/ directory contains both the Dockerfile and application code
    args: ['build', '-t', 'gcr.io/medo-458502/github.com/keminghe/medo:$COMMIT_SHA', '-f', 'prototype/Dockerfile', 'prototype']
    env: ['DOCKER_BUILDKIT=1']

options:
  # Only use Cloud Logging to avoid excessive log output and missing bucket error
  logging: CLOUD_LOGGING_ONLY
