[project]
name = "prototype"
version = "0.1.0"
description = "Multi-cloud data orchestrator prototype built using Google ADK."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "google-adk>=0.3.0",
]
